version: "3.7"
services:
    nginx:
        build:
            context: ./docker
            dockerfile: development/nginx/Dockerfile
        volumes:
            - ./:/app
        ports:
            - "80:80"
    php-fpm:
        build:
            context: ./docker
            dockerfile: development/php-fpm/Dockerfile
        volumes:
            - ./:/app
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            PHP_IDE_CONFIG: serverName=API
            DB_HOST: mysql
            DB_USER: app
            DB_PASSWORD: secret
            DB_NAME: app
            SENTRY_DSN: null
    php-cli:
        build:
            context: ./docker
            dockerfile: development/php-cli/Dockerfile
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            DB_HOST: mysql
            DB_USER: app
            DB_PASSWORD: secret
            DB_NAME: app
            SENTRY_DSN: null
        volumes:
            - ./:/app
        working_dir: /app
        tty: true
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: app
            MYSQL_PASSWORD: secret
            MYSQL_DATABASE: app
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - "33061:3306"
    nodejs:
        image: node:10.11-jessie
        volumes:
            - ./:/app
        working_dir: /app
        tty: true

volumes:
    mysql:
